apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab-dev

resources:
  - ../../../apps/bases/react-client

# This is the line your CI pipeline will bump on every deploy:
images:
  - name: nginx
    newName: ghcr.io/mercura/react-client
    newTag: v1
