apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab-dev

resources:
  - ../../../apps/bases/react-client

# This is the line your CI pipeline will bump on every deploy:
images:
  - name: nginx
    newName: ghcr.io/mercura/react-client
    newTag: "c4b24d1953b65d0d2727f2f8734663e8e4788e1d"
